In [39]:
#Nama : Ardhien Fadhillah Suhartono
#NIM  : 1103204137

****PyTorch****

PyTorch adalah sebuah library machine learning dan deep learning yang sangat populer. PyTorch menyediakan alat yang kuat untuk mengembangkan model machine learning, terutama model neural network. Berikut adalah beberapa konsep dasar atau fondasi (fundamentals) PyTorch:

1. **Tensor:**
   - Tensor adalah struktur data utama dalam PyTorch. Mirip dengan array multidimensi, tensor dapat berupa skalar (0D), vektor (1D), matriks (2D), atau tensor dengan dimensi lebih tinggi.
   - Operasi tensor yang efisien dan fleksibel memungkinkan pengolahan data numerik dengan mudah.

2. **Autograd:**
   - PyTorch menyediakan modul autograd yang otomatis menghitung gradien (derivative) dari operasi-operasi tensor.
   - Ini sangat berguna dalam pelatihan model machine learning karena mempermudah perhitungan gradien yang diperlukan untuk memperbarui parameter model.

3. **Model dan Layers:**
   - PyTorch memungkinkan definisi model secara dinamis menggunakan kelas Python.
   - Modul `torch.nn` menyediakan berbagai lapisan (layers) dan fungsi aktivasi yang digunakan untuk membangun model neural network.

4. **Optimizers:**
   - PyTorch menyediakan berbagai algoritma optimasi dalam modul `torch.optim` seperti SGD (Stochastic Gradient Descent), Adam, dan lain-lain. Optimizers ini digunakan untuk mengoptimalkan parameter model selama pelatihan.

5. **Dataset dan DataLoader:**
   - Modul `torch.utils.data` menyediakan fasilitas untuk memuat dan mengelola data dengan mudah.
   - DataLoader memudahkan dalam mengatur dan membagi data menjadi batch-batch untuk pelatihan model.

6. **Training Loop:**
   - Pelatihan model dalam PyTorch melibatkan iterasi melalui dataset, menghitung gradien, dan memperbarui parameter model.
   - PyTorch menyediakan struktur yang intuitif untuk membuat loop pelatihan dengan menggunakan autograd untuk perhitungan gradien.

7. **GPU Acceleration:**
   - PyTorch mendukung pelatihan model pada GPU, yang dapat signifikan meningkatkan kecepatan pelatihan, terutama untuk model yang kompleks.

8. **PyTorch Hub:**
   - PyTorch Hub adalah repositori model yang dapat digunakan untuk berbagi, menemukan, dan menggunakan pre-trained model PyTorch.

9. **Ecosystem:**
   - PyTorch memiliki ekosistem yang aktif dan mendukung berbagai proyek dan komunitas, termasuk dukungan komprehensif dari industri dan riset.

Dengan memahami konsep-konsep dasar tersebut, pengguna dapat membangun, melatih, dan menerapkan model machine learning dengan PyTorch secara efektif.

In [40]:
import torch
torch.__version__

'2.1.0+cu121'

Kode di atas adalah kode Python yang menggunakan library PyTorch untuk machine learning. Kode tersebut berfungsi untuk menampilkan versi PyTorch yang sedang digunakan. Mari kita bahas lebih detail:

```python
import torch
```

Baris ini mengimpor modul `torch` dari PyTorch. PyTorch adalah sebuah library open-source untuk komputasi numerik yang mendukung pembelajaran mesin dan jaringan neural.

```python
torch.__version__
```

Baris ini mencetak versi PyTorch yang sedang digunakan. Operator `__version__` digunakan untuk mengakses atribut versi dari objek `torch`. Ketika kode dijalankan, ini akan mencetak versi PyTorch yang terinstal.

Jadi, secara keseluruhan, kode tersebut hanya digunakan untuk menunjukkan versi PyTorch yang sedang digunakan pada lingkungan Python yang terkait. Jika Anda menjalankan kode ini, Anda akan melihat versi PyTorch yang tercetak sebagai outputnya.

In [41]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Dalam kode yang diberikan, Anda membuat sebuah skalar menggunakan PyTorch. Sebuah skalar adalah tensor dengan rank 0, yang berarti ia tidak memiliki dimensi. Dalam hal ini, nilai skalar tersebut adalah 7. Mari kita jelaskan baris-baris kode tersebut:

```python
# Scalar
scalar = torch.tensor(7)
```

- `torch.tensor(7)`: Membuat tensor PyTorch dengan nilai 7. Karena tidak ada dimensi yang disertakan, ini adalah skalar atau tensor dengan rank 0.
  
```python
scalar
```

- Baris ini sebenarnya mencetak atau mengembalikan nilai skalar yang telah dibuat. Jika Anda mengeksekusi baris ini, Anda akan melihat output yang menampilkan nilai skalar, yaitu `tensor(7)`.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah skalar dengan nilai 7 menggunakan PyTorch. Skalar ini dapat digunakan dalam berbagai operasi tensor dan merupakan contoh paling sederhana dari struktur data tensor yang disediakan oleh PyTorch.

In [42]:
scalar.ndim

0

Kode `scalar.ndim` tidak akan berfungsi secara langsung untuk skalar tersebut. Hal ini disebabkan oleh fakta bahwa skalar (tensor dengan rank 0) tidak memiliki dimensi (dimensi = 0), sehingga pemanggilan atribut `ndim` (yang umumnya digunakan untuk mendapatkan jumlah dimensi) pada skalar tidak valid.

Jika Anda mencoba menjalankan `scalar.ndim`, Anda akan mungkin menghadapi AttributeError, karena skalar tidak memiliki atribut `ndim`.

Sebagai alternatif, Anda dapat menggunakan `scalar.dim()` untuk mendapatkan jumlah dimensi. Namun, seperti yang telah disebutkan sebelumnya, untuk skalar, nilai ini akan selalu 0, karena skalar tidak memiliki dimensi.

Contoh penggunaan:

```python
scalar.dim()  # Output: 0
```

In [43]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Kode `scalar.item()` digunakan untuk mendapatkan nilai Python dari dalam sebuah tensor. Namun, perlu diingat bahwa ini hanya berfungsi jika tensor tersebut hanya memiliki satu elemen.

Dalam kasus skalar (tensor dengan rank 0), ini pasti akan berfungsi, karena skalar hanya memiliki satu elemen. Jika tensor memiliki lebih dari satu elemen, pemanggilan `item()` akan menyebabkan `ValueError`.

Contoh penggunaan:

```python
# scalar is a tensor with a single element (rank 0)
scalar_value = scalar.item()
print(scalar_value)  # Output: 7
```

Namun, jika Anda memiliki tensor dengan lebih dari satu elemen, Anda harus berhati-hati saat menggunakan `item()`, dan pastikan bahwa tensor tersebut benar-benar hanya memiliki satu elemen untuk menghindari kesalahan runtime.

In [44]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Dalam kode di atas, Anda membuat sebuah vektor menggunakan PyTorch. Vektor adalah tensor dengan rank 1, yang berarti memiliki satu dimensi. Dalam hal ini, vektor tersebut memiliki dua elemen, yaitu 7 dan 7. Mari kita jelaskan baris-baris kode tersebut:

```python
# Vector
vector = torch.tensor([7, 7])
```

- `torch.tensor([7, 7])`: Membuat tensor PyTorch yang merupakan vektor dengan dua elemen, yaitu 7 dan 7.

```python
vector
```

- Baris ini mencetak atau mengembalikan nilai vektor yang telah dibuat. Jika Anda mengeksekusi baris ini, Anda akan melihat output yang menampilkan nilai vektor, yaitu `tensor([7, 7])`.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah vektor dengan dua elemen (7 dan 7) menggunakan PyTorch. Vektor ini dapat digunakan dalam berbagai operasi tensor dan merupakan contoh dari tensor dengan rank 1.

In [45]:
# Check the number of dimensions of vector
vector.ndim

1


`vector.ndim` pada PyTorch tidak memberikan hasil yang sesuai dengan konvensi umum untuk jumlah dimensi. Pada umumnya, ini mungkin mengembalikan `1`, tetapi sebenarnya, vektor dianggap sebagai tensor satu dimensi dalam PyTorch. Untuk mendapatkan panjang (jumlah elemen) dari vektor, Anda dapat menggunakan `len(vector)` atau `vector.size(0)`.

In [46]:
# Check shape of vector
vector.shape

torch.Size([2])

Anda dapat menggunakan atribut `shape` untuk memeriksa dimensi dari sebuah tensor dalam PyTorch, termasuk vektor. Mari kita lihat contohnya:

```python
# Check the shape of the vector
vector.shape
```

Hasil dari `vector.shape` akan memberikan tuple yang menyatakan panjang atau ukuran dari setiap dimensi. Untuk vektor (tensor 1D), tuple tersebut akan berisi satu elemen yang merupakan panjang dari vektor.

Sebagai contoh, jika `vector` adalah sebuah vektor dengan panjang 2, maka `vector.shape` akan mengembalikan `(2,)`.

Jadi, output dari `vector.shape` akan memberikan informasi tentang ukuran atau panjang vektor tersebut.

In [47]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Dalam kode di atas, Anda membuat sebuah matriks menggunakan PyTorch. Matriks adalah tensor dengan rank 2, yang berarti memiliki dua dimensi (baris dan kolom). Dalam hal ini, matriks tersebut memiliki dua baris dan dua kolom, dengan elemen-elemen 7, 8, 9, dan 10. Mari kita jelaskan baris-baris kode tersebut:

```python
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
```

- `torch.tensor([[7, 8], [9, 10]])`: Membuat tensor PyTorch yang merupakan matriks dengan dua baris dan dua kolom, dengan elemen-elemen yang ditentukan dalam daftar bersarang.

```python
MATRIX
```

- Baris ini mencetak atau mengembalikan nilai matriks yang telah dibuat. Jika Anda mengeksekusi baris ini, Anda akan melihat output yang menampilkan nilai matriks, yaitu:

```
tensor([[ 7,  8],
        [ 9, 10]])
```

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah matriks 2x2 dengan elemen-elemen yang ditentukan menggunakan PyTorch. Matriks ini dapat digunakan dalam berbagai operasi tensor dan merupakan contoh dari tensor dengan rank 2.

In [48]:
# Check number of dimensions
MATRIX.ndim

2

Anda dapat menggunakan atribut `ndim` untuk mengetahui jumlah dimensi dari tensor, termasuk matriks. Mari kita lihat bagaimana Anda dapat menggunakannya pada matriks `MATRIX` yang telah Anda buat:

```python
# Check the number of dimensions of the matrix
MATRIX.ndim
```

Hasil dari `MATRIX.ndim` akan memberikan jumlah dimensi dari matriks tersebut. Untuk matriks, yang memiliki dua dimensi (baris dan kolom), hasilnya seharusnya adalah `2`.

Jadi, jika Anda mengeksekusi baris kode di atas, Anda akan mendapatkan output yang menyatakan jumlah dimensi dari matriks `MATRIX`.

In [49]:
MATRIX.shape

torch.Size([2, 2])

Anda dapat menggunakan atribut `shape` untuk memeriksa dimensi dari sebuah tensor dalam PyTorch, termasuk matriks. Mari kita lihat bagaimana Anda dapat menggunakannya pada matriks `MATRIX`:

```python
# Check the shape of the matrix
MATRIX.shape
```

Hasil dari `MATRIX.shape` akan memberikan tuple yang menyatakan panjang atau ukuran dari setiap dimensi. Untuk matriks, tuple tersebut akan berisi dua elemen yang mewakili jumlah baris dan jumlah kolom.

Jadi, jika `MATRIX` adalah sebuah matriks 2x2, maka `MATRIX.shape` akan mengembalikan `(2, 2)`.

Output dari `MATRIX.shape` memberikan informasi tentang ukuran atau panjang dari matriks dalam bentuk tuple yang menyatakan jumlah baris dan jumlah kolom.

In [50]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Dalam kode di atas, Anda membuat sebuah tensor tiga dimensi menggunakan PyTorch. Tensor ini memiliki rank 3, yang berarti memiliki tiga dimensi: dalam hal ini, dimensi pertama memiliki panjang 1, dimensi kedua memiliki panjang 3, dan dimensi ketiga memiliki panjang 3. Mari kita jelaskan baris-baris kode tersebut:

```python
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
```

- `torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])`: Membuat tensor PyTorch yang memiliki rank 3 dengan panjang 1 pada dimensi pertama, panjang 3 pada dimensi kedua, dan panjang 3 pada dimensi ketiga.

```python
TENSOR
```

- Baris ini mencetak atau mengembalikan nilai tensor yang telah dibuat. Jika Anda mengeksekusi baris ini, Anda akan melihat output yang menampilkan nilai tensor, yaitu:

```
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
```

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor tiga dimensi dengan elemen-elemen yang ditentukan menggunakan PyTorch. Tensor ini dapat digunakan dalam berbagai operasi tensor dan merupakan contoh dari tensor dengan rank 3.

In [51]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [52]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4285, 0.4315, 0.1108, 0.4967],
         [0.6154, 0.4833, 0.8958, 0.8124],
         [0.3651, 0.9521, 0.1595, 0.8247]]),
 torch.float32)

Dalam kode di atas, Anda membuat sebuah tensor acak menggunakan PyTorch. Berikut adalah penjelasan singkat:

```python
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
```

- `torch.rand(size=(3, 4))`: Membuat tensor PyTorch dengan ukuran (shape) 3x4 yang berisi nilai-nilai acak antara 0 dan 1. Fungsi `torch.rand()` digunakan untuk menghasilkan nilai acak dari distribusi seragam.

```python
random_tensor
```

- Baris ini mencetak atau mengembalikan nilai tensor acak yang telah dibuat.

```python
random_tensor.dtype
```

- Baris ini mengembalikan tipe data (dtype) dari tensor tersebut. Tipe data tensor acak yang dihasilkan umumnya adalah float32.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor acak berukuran 3x4 dengan nilai-nilai acak antara 0 dan 1, dan kemudian menampilkan tensor tersebut beserta tipe datanya.

In [54]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Dalam kode di atas, Anda mencoba membuat tensor acak dengan ukuran (224, 224, 3). Namun, perlu dicatat bahwa PyTorch tidak langsung mendukung pembuatan tensor tiga dimensi dengan bentuk seperti itu. PyTorch lebih umum digunakan untuk tensor dengan dua atau lebih dimensi, sementara tensor tiga dimensi biasanya digunakan untuk merepresentasikan citra dengan dimensi (tinggi, lebar, saluran).

Anda mungkin ingin membuat tensor berukuran (224, 224, 3) sebagai tensor citra dengan dimensi tinggi, lebar, dan saluran warna (RGB). Dalam kasus ini, Anda bisa membuat tensor berukuran (3, 224, 224) atau (224, 224, 3), tergantung pada preferensi urutan dimensi saluran warna.

Berikut contoh untuk membuat tensor dengan dimensi (3, 224, 224):

```python
# Create a random image-sized tensor with channels last (224, 224, 3)
random_image_size_tensor_channels_last = torch.rand(size=(3, 224, 224))
```

Atau, jika Anda ingin menggunakan urutan dimensi (224, 224, 3):

```python
# Create a random image-sized tensor with channels first (3, 224, 224)
random_image_size_tensor_channels_first = torch.rand(size=(224, 224, 3)).permute(2, 0, 1)
```

Dengan cara ini, Anda dapat membuat tensor yang lebih sesuai dengan representasi citra RGB.

In [55]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Dalam kode di atas, Anda membuat tensor berisi semua nilai nol menggunakan PyTorch. Berikut adalah penjelasan singkat:

```python
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
```

- `torch.zeros(size=(3, 4))`: Membuat tensor PyTorch berukuran 3x4 yang diisi dengan nilai nol.

```python
zeros
```

- Baris ini mencetak atau mengembalikan nilai tensor yang telah dibuat.

```python
zeros.dtype
```

- Baris ini mengembalikan tipe data (dtype) dari tensor tersebut. Secara default, tensor berisi nol akan memiliki tipe data float32.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor berukuran 3x4 yang berisi semua nilai nol menggunakan PyTorch, dan kemudian menampilkan tensor tersebut beserta tipe datanya.

In [56]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Dalam kode di atas, Anda membuat tensor berisi semua nilai satu menggunakan PyTorch. Berikut adalah penjelasan singkat:

```python
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
```

- `torch.ones(size=(3, 4))`: Membuat tensor PyTorch berukuran 3x4 yang diisi dengan nilai satu.

```python
ones
```

- Baris ini mencetak atau mengembalikan nilai tensor yang telah dibuat.

```python
ones.dtype
```

- Baris ini mengembalikan tipe data (dtype) dari tensor tersebut. Secara default, tensor berisi nilai satu akan memiliki tipe data float32.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor berukuran 3x4 yang berisi semua nilai satu menggunakan PyTorch, dan kemudian menampilkan tensor tersebut beserta tipe datanya.

In [57]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-57-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Dalam kode di atas, Anda menggunakan fungsi `torch.arange()` untuk membuat tensor yang berisi rentang nilai dari 0 hingga 10. Penting untuk dicatat bahwa `torch.range()` sudah tidak direkomendasikan (deprecated), dan sebaiknya menggunakan `torch.arange()`.

Berikut adalah penjelasan singkat:

```python
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10)  # Note: Deprecated, may return an error in the future

# Create a range of values 0 to 10 using torch.arange()
zero_to_ten = torch.arange(start=0, end=10, step=1)
```

- `torch.arange(start=0, end=10, step=1)`: Membuat tensor PyTorch yang berisi rentang nilai dari 0 hingga 10 (tidak termasuk 10) dengan langkah sebesar 1.

```python
zero_to_ten
```

- Baris ini mencetak atau mengembalikan nilai tensor yang telah dibuat.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor yang berisi rentang nilai dari 0 hingga 9 menggunakan `torch.arange()`, menggantikan penggunaan `torch.range()` yang sudah tidak direkomendasikan.

In [58]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Dalam kode di atas, Anda membuat tensor dengan tipe data default `float32` menggunakan PyTorch. Berikut adalah penjelasan singkat:

```python
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,           # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None,          # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations performed on the tensor are recorded
```

- `torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)`: Membuat tensor PyTorch dari list yang diberikan. Tipe data (dtype) secara default akan menjadi `float32` jika tidak ditentukan secara eksplisit.

```python
float_32_tensor.shape
```

- Baris ini mengembalikan bentuk (shape) dari tensor.

```python
float_32_tensor.dtype
```

- Baris ini mengembalikan tipe data (dtype) dari tensor. Secara default, tipe data tensor akan menjadi `float32`.

```python
float_32_tensor.device
```

- Baris ini mengembalikan perangkat (device) tempat tensor berada. Jika tidak ditentukan secara eksplisit, ini akan menggunakan perangkat default.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor dengan tipe data default `float32`, bentuk (shape) yang sesuai dengan list yang diberikan, dan tanpa merekam gradien (`requires_grad=False`).

In [60]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Dalam kode di atas, Anda membuat tensor dengan tipe data `float16` menggunakan PyTorch. Berikut adalah penjelasan singkat:

```python
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half would also work
```

- `torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)`: Membuat tensor PyTorch dari list yang diberikan dengan menentukan tipe data (dtype) secara eksplisit sebagai `float16`. Anda juga dapat menggunakan `torch.half` sebagai alternatif untuk menyatakan tipe data `float16`.

```python
float_16_tensor.dtype
```

- Baris ini mengembalikan tipe data (dtype) dari tensor. Dalam hal ini, tipe data tensor adalah `float16`.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor dengan tipe data `float16`, yang merupakan representasi floating-point dengan setengah presisi, dan kemudian menampilkan tipe datanya.

In [61]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6274, 0.5078, 0.5410, 0.1678],
        [0.3528, 0.5445, 0.1425, 0.8973],
        [0.0815, 0.5017, 0.1450, 0.3772]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Dalam kode di atas, Anda membuat sebuah tensor acak menggunakan PyTorch dan menampilkan beberapa informasi detail tentang tensor tersebut. Berikut adalah penjelasan singkat:

```python
# Create a tensor
some_tensor = torch.rand(3, 4)
```

- `torch.rand(3, 4)`: Membuat tensor PyTorch berukuran 3x4 yang diisi dengan nilai acak antara 0 dan 1.

```python
# Find out details about it
print(some_tensor)
```

- Baris ini mencetak nilai tensor yang telah dibuat.

```python
print(f"Shape of tensor: {some_tensor.shape}")
```

- Baris ini mencetak atau menampilkan bentuk (shape) dari tensor, yaitu 3 baris dan 4 kolom.

```python
print(f"Datatype of tensor: {some_tensor.dtype}")
```

- Baris ini mencetak atau menampilkan tipe data (dtype) dari tensor. Secara default, tensor acak seperti ini akan memiliki tipe data `float32`.

```python
print(f"Device tensor is stored on: {some_tensor.device}")  # will default to CPU
```

- Baris ini mencetak atau menampilkan perangkat (device) tempat tensor disimpan. Jika tidak ditentukan secara eksplisit, ini akan menggunakan perangkat default, yang dalam kasus ini adalah CPU.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor acak, dan kemudian menampilkan beberapa detail tentang tensor tersebut, seperti nilai, bentuk, tipe data, dan perangkat penyimpanan.

In [62]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

Dalam kode di atas, Anda membuat sebuah tensor dengan nilai `[1, 2, 3]` menggunakan PyTorch, dan kemudian menambahkan angka 10 ke setiap elemennya. Berikut adalah penjelasan singkat:

```python
# Create a tensor of values
tensor = torch.tensor([1, 2, 3])
```

- `torch.tensor([1, 2, 3])`: Membuat tensor PyTorch dari list yang diberikan, yaitu tensor dengan elemen `[1, 2, 3]`.

```python
tensor + 10
```

- Baris ini menambahkan angka 10 ke setiap elemen tensor menggunakan operator penambahan (`+`). Hasilnya adalah tensor baru dengan nilai `[11, 12, 13]`, dan tensor asli tidak berubah.

Jadi, secara keseluruhan, kode tersebut menciptakan sebuah tensor dengan nilai awal `[1, 2, 3]` dan kemudian menambahkan angka 10 ke setiap elemennya, menghasilkan tensor baru dengan nilai `[11, 12, 13]`.

In [63]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [64]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [65]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [66]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [67]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [68]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [69]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Dalam kode di atas, Anda melakukan perkalian element-wise (perkalian setiap elemen dengan elemen yang setara) pada suatu tensor. Berikut adalah penjelasan singkat:

```python
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
```

- Baris ini mencetak tensor yang sama di kedua sisi operator perkalian `*`, menunjukkan bahwa kita akan melakukan perkalian element-wise.

```python
print("Equals:", tensor * tensor)
```

- Baris ini mencetak hasil perkalian element-wise dari tensor dengan dirinya sendiri. Hasilnya adalah tensor baru dengan nilai `[1, 4, 9]`, di mana setiap elemen merupakan hasil dari perkalian elemen yang setara.

Jadi, secara keseluruhan, kode tersebut melakukan perkalian element-wise pada tensor `[1, 2, 3]` dengan dirinya sendiri, menghasilkan tensor baru dengan nilai `[1, 4, 9]`.

In [70]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Pada kode di atas, Anda menggunakan atribut `shape` untuk mendapatkan bentuk (shape) dari tensor PyTorch. Berikut adalah penjelasan singkat:

```python
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape
```

- `torch.tensor([1, 2, 3])`: Membuat tensor PyTorch dari list yang diberikan, yaitu tensor dengan elemen `[1, 2, 3]`.

```python
tensor.shape
```

- Baris ini mengembalikan bentuk (shape) dari tensor. Pada kasus ini, tensor tersebut adalah tensor 1 dimensi (rank 1), sehingga bentuknya adalah `(3,)`, yang berarti terdapat 3 elemen dalam satu dimensi.

Jadi, secara keseluruhan, kode tersebut menciptakan tensor `[1, 2, 3]` dan kemudian menampilkan bentuk (shape) dari tensor tersebut.

In [71]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

Dalam kode di atas, Anda melakukan perkalian element-wise pada suatu tensor dengan dirinya sendiri. Namun, karena tensor tersebut adalah tensor satu dimensi (vektor), hasilnya adalah perkalian element-wise dari setiap elemen dengan dirinya sendiri. Berikut adalah penjelasan singkat:

```python
# Element-wise matrix multiplication
tensor * tensor
```

- Baris ini melakukan perkalian element-wise pada tensor dengan dirinya sendiri. Karena tensor `tensor` adalah tensor satu dimensi (vektor), hasilnya adalah vektor baru dengan nilai `[1, 4, 9]`, di mana setiap elemen merupakan hasil dari perkalian elemen yang setara.

Jadi, secara keseluruhan, kode tersebut menghasilkan vektor baru dengan nilai `[1, 4, 9]`, yang merupakan hasil dari perkalian element-wise dari tensor `[1, 2, 3]` dengan dirinya sendiri.

In [72]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [73]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [74]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 118 µs, sys: 21 µs, total: 139 µs
Wall time: 145 µs


tensor(14)

Dalam kode di atas, Anda melakukan perkalian matriks secara manual dengan menggunakan loop `for`. Penggunaan loop `for` untuk operasi matriks dapat menjadi mahal secara komputasi, dan sebaiknya dihindari jika mungkin. Untuk melakukan perkalian element-wise dan menghitung jumlahnya, Anda dapat menggunakan fungsi PyTorch atau NumPy yang dioptimalkan. Berikut adalah penjelasan singkat:

```python
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value
```

- `%time` adalah magic command di Jupyter Notebook yang digunakan untuk mengukur waktu eksekusi sel kode di sel yang sama. `%%time` digunakan untuk mengukur waktu eksekusi seluruh sel kode.

- Baris kedua (`for` loop) melakukan perkalian element-wise dan menghitung jumlahnya secara manual menggunakan loop `for`.

Jika tujuan Anda adalah untuk menghitung jumlah dari kuadrat setiap elemen dalam tensor, ada cara yang lebih efisien menggunakan operasi vektorisasi di PyTorch atau NumPy tanpa perlu menggunakan loop `for`. Contohnya dapat dilihat di kode sebelumnya yang menggunakan `tensor * tensor`.

Penting untuk mencatat bahwa menggunakan operasi vektorisasi biasanya lebih efisien dan lebih disukai daripada menggunakan loop `for` untuk operasi matriks atau vektor dalam PyTorch atau NumPy.

In [75]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 34.1 µs


tensor(14)

In [76]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

Pada kode di atas, Anda mencoba melakukan perkalian matriks menggunakan `torch.matmul()`, namun akan mendapatkan kesalahan. Kesalahan ini muncul karena bentuk (shape) dari matriks `tensor_A` dan `tensor_B` tidak memenuhi persyaratan untuk perkalian matriks yang valid.

Untuk dapat melakukan perkalian matriks dengan benar, jumlah kolom dari matriks pertama (`tensor_A`) harus sama dengan jumlah baris dari matriks kedua (`tensor_B`). Dalam hal ini, kedua matriks memiliki bentuk (shape) 3x2, yang berarti matriks pertama memiliki 3 baris dan 2 kolom, sedangkan matriks kedua memiliki 2 baris dan 2 kolom. Jumlah kolom dari matriks pertama (2) tidak sama dengan jumlah baris dari matriks kedua (2), sehingga operasi perkalian matriks tidak dapat dilakukan.

Jika Anda ingin melakukan perkalian matriks yang valid, pastikan bahwa jumlah kolom dari matriks pertama sama dengan jumlah baris dari matriks kedua. Misalnya:

```python
result_matrix = torch.matmul(tensor_A, tensor_B.t())  # Menggunakan tensor_B.t() untuk mentransposisi matriks kedua
```

Dengan cara ini, matriks kedua akan memiliki bentuk (shape) 2x3, sehingga operasi perkalian matriks dapat dilakukan.

In [77]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [78]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [79]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Dalam kode di atas, Anda berhasil melakukan operasi perkalian matriks setelah mentransposisi `tensor_B` agar bentuknya sesuai untuk operasi perkalian matriks. Berikut adalah penjelasan singkat:

```python
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
```

- Pada baris pertama, Anda mencetak bentuk (shape) matriks `tensor_A` dan `tensor_B`.

- Baris kedua mencetak bentuk (shape) matriks `tensor_A` yang tetap sama dan bentuk (shape) matriks `tensor_B` setelah ditransposisi.

- Baris ketiga memberikan penjelasan bahwa operasi perkalian matriks dilakukan karena jumlah kolom dari `tensor_A` (2) sekarang sama dengan jumlah baris dari `tensor_B.T` (2).

- Baris kelima mencetak hasil operasi perkalian matriks antara `tensor_A` dan `tensor_B.T`.

- Baris keenam mencetak bentuk (shape) dari hasil matriks.

Jadi, dengan mentransposisi `tensor_B`, Anda berhasil melakukan operasi perkalian matriks dengan benar.

In [80]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [81]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Dalam kode di atas, Anda menggunakan modul PyTorch `torch.nn.Linear` untuk membuat lapisan linear. Anda juga menetapkan benih (seed) dengan `torch.manual_seed(42)` untuk membuat hasil eksperimen Anda menjadi reproduktif. Berikut adalah penjelasan singkat:

```python
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
```

- Baris ini menetapkan benih (seed) untuk generator angka acak PyTorch, sehingga hasil eksperimen ini dapat direproduksi.

```python
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6)
```

- Baris ini membuat objek lapisan linear dengan dua input (in_features) dan enam output (out_features).

```python
x = tensor_A
output = linear(x)
```

- Baris ini menggunakan lapisan linear untuk melakukan transformasi pada tensor `tensor_A`.

```python
print(f"Input shape: {x.shape}\n")
```

- Baris ini mencetak bentuk (shape) dari tensor input `x` (matriks `tensor_A`).

```python
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")
```

- Baris ini mencetak hasil transformasi tensor input melalui lapisan linear serta bentuk (shape) dari hasilnya.

Jadi, secara keseluruhan, kode tersebut membuat lapisan linear menggunakan PyTorch, melakukan transformasi pada tensor input, dan mencetak hasil transformasi beserta bentuk (shape) dari input dan output.

In [82]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


Dalam kode di atas, Anda mencetak nilai minimum, maksimum, rata-rata, dan jumlah dari tensor `x` (matriks `tensor_A`). Berikut adalah penjelasan singkat:

```python
print(f"Minimum: {x.min()}")
```

- Baris ini mencetak nilai minimum dari tensor `x` (matriks `tensor_A`).

```python
print(f"Maximum: {x.max()}")
```

- Baris ini mencetak nilai maksimum dari tensor `x` (matriks `tensor_A`).

```python
# print(f"Mean: {x.mean()}") # this will error
```

- Baris ini memberikan contoh bagaimana memanggil `mean()` pada tensor integer dapat menyebabkan kesalahan. PyTorch memerlukan tipe data float untuk operasi rata-rata.

```python
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
```

- Baris ini mengubah tipe data tensor menjadi float32 dan kemudian menghitung rata-ratanya.

```python
print(f"Sum: {x.sum()}")
```

- Baris ini mencetak jumlah dari semua elemen dalam tensor `x` (matriks `tensor_A`).

Jadi, secara keseluruhan, kode tersebut memberikan informasi statistik tentang tensor `x`, termasuk nilai minimum, maksimum, rata-rata (setelah mengubah tipe data menjadi float), dan jumlah dari elemen-elemen tensor tersebut.

In [84]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [85]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Dalam kode di atas, Anda membuat tensor menggunakan `torch.arange()` dan kemudian mencetak indeks dari nilai maksimum dan minimum dalam tensor tersebut. Berikut adalah penjelasan singkat:

```python
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")
```

- Baris ini membuat tensor menggunakan `torch.arange()`, yang menghasilkan tensor berisi nilai dari 10 hingga 90 (dengan langkah 10).

```python
# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")
```

- Baris-baris ini mencetak indeks dari nilai maksimum dan minimum dalam tensor menggunakan `argmax()` dan `argmin()`. `argmax()` mengembalikan indeks dari nilai maksimum, sedangkan `argmin()` mengembalikan indeks dari nilai minimum.

Jadi, secara keseluruhan, kode tersebut menciptakan tensor dan kemudian mencetak indeks dari nilai maksimum dan minimum dalam tensor tersebut.

In [86]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [87]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [88]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [89]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [90]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [91]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [92]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [93]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [94]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Dalam kode di atas, Anda menggunakan metode `squeeze()` untuk menghapus dimensi yang memiliki panjang 1 dari suatu tensor. Berikut adalah penjelasan singkat:

```python
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
```

- Baris-baris ini mencetak tensor sebelum dimensinya diubah dan bentuk (shape) dari tensor tersebut.

```python
# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
```

- Baris ini menggunakan metode `squeeze()` untuk menghapus dimensi yang memiliki panjang 1 dari tensor `x_reshaped`. Hasilnya disimpan dalam tensor baru `x_squeezed`.

```python
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
```

- Baris-baris ini mencetak tensor setelah dimensinya diubah menggunakan `squeeze()` dan bentuk (shape) dari tensor yang baru.

Jadi, secara keseluruhan, kode tersebut mencetak tensor sebelum dan setelah penghapusan dimensi yang memiliki panjang 1 dengan menggunakan metode `squeeze()`.

In [95]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


Dalam kode di atas, Anda menggunakan metode `unsqueeze()` untuk menambahkan dimensi baru pada suatu tensor. Berikut adalah penjelasan singkat:

```python
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
```

- Baris-baris ini mencetak tensor sebelum dimensinya diubah dan bentuk (shape) dari tensor tersebut.

```python
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
```

- Baris ini menggunakan metode `unsqueeze(dim=0)` untuk menambahkan dimensi baru pada tensor `x_squeezed`. Dimensi baru ini ditempatkan di indeks 0, sehingga bentuk (shape) dari tensor menjadi `(1, n)`, di mana `n` adalah panjang dimensi sebelumnya.

```python
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
```

- Baris-baris ini mencetak tensor setelah dimensinya diubah menggunakan `unsqueeze()` dan bentuk (shape) dari tensor yang baru.

Jadi, secara keseluruhan, kode tersebut mencetak tensor sebelum dan setelah penambahan dimensi baru menggunakan `unsqueeze()`.

In [96]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Dalam kode di atas, Anda membuat tensor dengan bentuk (shape) tertentu menggunakan `torch.rand()` dan kemudian menggunakan metode `permute()` untuk merubah urutan sumbu (axis) tensor. Berikut adalah penjelasan singkat:

```python
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))
```

- Baris ini membuat tensor dengan bentuk (shape) `(224, 224, 3)` yang diisi dengan nilai acak antara 0 dan 1.

```python
# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0
```

- Baris ini menggunakan metode `permute(2, 0, 1)` untuk merubah urutan sumbu (axis) tensor. Setelah operasi ini, urutan sumbu tensor menjadi `(3, 224, 224)`.

```python
print(f"Previous shape: {x_original.shape}")
```

- Baris ini mencetak bentuk (shape) tensor sebelum permutasi.

```python
print(f"New shape: {x_permuted.shape}")
```

- Baris ini mencetak bentuk (shape) tensor setelah permutasi.

Jadi, secara keseluruhan, kode tersebut menciptakan tensor dengan bentuk (shape) `(224, 224, 3)`, dan kemudian menggunakan `permute()` untuk merubah urutan sumbu (axis) tensor sehingga bentuknya menjadi `(3, 224, 224)`.

In [97]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Dalam kode di atas, Anda membuat tensor `x` menggunakan `torch.arange()` dan kemudian mereshape tensor tersebut menggunakan metode `reshape()`. Berikut adalah penjelasan singkat:

```python
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
```

- Baris ini membuat tensor `x` menggunakan `torch.arange(1, 10)` untuk menghasilkan tensor dengan nilai dari 1 hingga 9, dan kemudian menggunakan `reshape(1, 3, 3)` untuk mengubah bentuk tensor tersebut menjadi `(1, 3, 3)`.

```python
x, x.shape
```

- Baris ini mencetak tensor `x` beserta bentuk (shape)-nya.

Jadi, secara keseluruhan, kode tersebut menciptakan tensor `x` dengan nilai dari 1 hingga 9 dan bentuk (shape) `(1, 3, 3)`.

In [98]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Dalam kode di atas, Anda melakukan indeksing tensor secara bertahap menggunakan tanda kurung siku `[ ]`. Berikut adalah penjelasan singkat:

```python
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
```

- Baris ini mencetak hasil indeksing pertama, yaitu elemen dengan indeks 0 dari dimensi pertama tensor `x`. Hasilnya adalah tensor 2D `(3, 3)`.

```python
print(f"Second square bracket: {x[0][0]}")
```

- Baris ini mencetak hasil indeksing kedua, yaitu elemen dengan indeks 0 dari dimensi kedua tensor `x[0]`. Hasilnya adalah tensor 1D `(3,)`.

```python
print(f"Third square bracket: {x[0][0][0]}")
```

- Baris ini mencetak hasil indeksing ketiga, yaitu elemen dengan indeks 0 dari dimensi ketiga tensor `x[0][0]`. Hasilnya adalah nilai tunggal.

Jadi, secara keseluruhan, kode tersebut melakukan indeksing tensor secara bertahap untuk mengakses nilai dalam tensor `x`.

In [99]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [100]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [101]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [102]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [103]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Dalam kode di atas, Anda mengonversi NumPy array ke tensor PyTorch menggunakan `torch.from_numpy()`. Berikut adalah penjelasan singkat:

```python
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
```

- Baris ini membuat NumPy array `array` dengan nilai dari 1.0 hingga 7.0 menggunakan `np.arange(1.0, 8.0)`.

- Baris ini menggunakan `torch.from_numpy(array)` untuk mengonversi NumPy array menjadi tensor PyTorch. Harap diperhatikan bahwa tensor ini akan mengambil referensi ke array NumPy asli, sehingga perubahan pada tensor akan tercermin dalam array NumPy dan sebaliknya.

```python
array, tensor
```

- Baris ini mencetak NumPy array dan tensor PyTorch yang telah dibuat.

Jadi, secara keseluruhan, kode tersebut mengonversi NumPy array ke tensor PyTorch menggunakan `torch.from_numpy()`.

In [104]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [105]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Dalam kode di atas, Anda mengonversi tensor PyTorch ke NumPy array menggunakan metode `numpy()`. Berikut adalah penjelasan singkat:

```python
# Tensor to NumPy array
tensor = torch.ones(7)  # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()  # will be dtype=float32 unless changed
```

- Baris ini membuat tensor PyTorch `tensor` yang berisi tujuh elemen dengan nilai 1.0.

- Baris ini menggunakan `tensor.numpy()` untuk mengonversi tensor PyTorch menjadi NumPy array.

```python
tensor, numpy_tensor
```

- Baris ini mencetak tensor PyTorch dan NumPy array yang telah dibuat.

Jadi, secara keseluruhan, kode tersebut mengonversi tensor PyTorch ke NumPy array menggunakan metode `numpy()`. Perlu diingat bahwa perubahan pada tensor PyTorch akan tercermin dalam NumPy array dan sebaliknya, karena keduanya menggunakan memori yang sama.

In [106]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [107]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Dalam kode di atas, Anda membuat dua tensor acak `random_tensor_A` dan `random_tensor_B`, dan kemudian memeriksa apakah elemen-elemen tensor A sama dengan elemen-elemen tensor B. Berikut adalah penjelasan singkat:

```python
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
```

- Baris-baris ini membuat dua tensor acak `random_tensor_A` dan `random_tensor_B` dengan bentuk (shape) 3x4 menggunakan `torch.rand()`.

```python
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B
```

- Baris ini mencetak pesan dan kemudian melakukan perbandingan element-wise antara `random_tensor_A` dan `random_tensor_B` menggunakan operator `==`. Hasilnya adalah tensor boolean dengan ukuran yang sama seperti kedua tensor, yang menunjukkan apakah setiap elemen di kedua tensor tersebut sama.

Jadi, secara keseluruhan, kode tersebut menciptakan dua tensor acak dan memeriksa apakah elemen-elemen tensor A sama dengan elemen-elemen tensor B dengan melakukan perbandingan element-wise.

In [108]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Dalam kode di atas, Anda mengatur seed (benih) untuk generator angka acak PyTorch dan menggunakan fungsi `torch.rand()` untuk membuat dua tensor acak `random_tensor_C` dan `random_tensor_D`. Kemudian, Anda memeriksa apakah elemen-elemen tensor C sama dengan elemen-elemen tensor D. Berikut adalah penjelasan singkat:

```python
import torch
import random

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
```

- Baris-baris ini mengatur seed (benih) untuk generator angka acak PyTorch menggunakan `torch.manual_seed()` dan membuat tensor acak `random_tensor_C` menggunakan `torch.rand(3, 4)`.

- Baris-baris selanjutnya mengatur seed (benih) kembali sebelum membuat tensor acak `random_tensor_D`, untuk memastikan bahwa generator angka acak menghasilkan nilai yang sama ketika seed (benih) yang sama digunakan.

```python
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D
```

- Baris ini mencetak pesan dan kemudian melakukan perbandingan element-wise antara `random_tensor_C` dan `random_tensor_D` menggunakan operator `==`. Hasilnya adalah tensor boolean dengan ukuran yang sama seperti kedua tensor, yang menunjukkan apakah setiap elemen di kedua tensor tersebut sama.

Jadi, secara keseluruhan, kode tersebut menggunakan seed (benih) yang sama untuk menghasilkan tensor acak yang identik `random_tensor_C` dan `random_tensor_D`.

In [109]:
!nvidia-smi

Wed Jan  3 11:08:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

`!nvidia-smi` adalah perintah yang digunakan untuk menampilkan informasi tentang kartu grafis NVIDIA yang terpasang pada sistem komputer. Fungsinya mencakup informasi seperti model GPU, penggunaan memori, suhu, dan status kinerja lainnya. Perintah ini sering digunakan untuk memantau dan mengelola GPU, terutama dalam konteks pengembangan dan pemrograman yang melibatkan komputasi GPU, seperti pelatihan model deep learning menggunakan GPU.

In [110]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [111]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [112]:
# Count number of devices
torch.cuda.device_count()

1

In [113]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Dalam kode di atas, Anda membuat tensor PyTorch pada CPU dan kemudian memindahkannya ke GPU (jika tersedia). Berikut adalah penjelasan singkat:

```python
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)
```

- Baris-baris ini membuat tensor PyTorch `tensor` pada CPU dengan menggunakan `torch.tensor([1, 2, 3])`.

```python
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
```

- Baris ini memindahkan tensor dari CPU ke GPU (jika GPU tersedia) dengan menggunakan metode `to(device)`. Harap diperhatikan bahwa variabel `device` harus didefinisikan sebelumnya dan menunjuk ke GPU.

```python
tensor_on_gpu
```

- Baris ini mencetak tensor yang sudah dipindahkan ke GPU.

Jadi, secara keseluruhan, kode tersebut menciptakan tensor pada CPU dan kemudian memindahkannya ke GPU (jika tersedia) menggunakan metode `to(device)`.

In [114]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

Benar, jika tensor berada di GPU, Anda tidak dapat langsung mengonversinya ke NumPy array menggunakan `numpy()` tanpa terlebih dahulu memindahkannya kembali ke CPU. Hal ini karena operasi NumPy biasanya dilakukan pada CPU. Jika Anda mencoba melakukannya pada GPU, akan muncul kesalahan.

Anda perlu mengirim tensor kembali ke CPU sebelum mengonversinya menjadi NumPy array. Misalnya:

```python
# Move tensor back to CPU
tensor_on_cpu = tensor_on_gpu.to('cpu')

# Now, you can convert it to NumPy array
numpy_array = tensor_on_cpu.numpy()
```

Dengan cara ini, Anda dapat mengonversi tensor yang awalnya berada di GPU menjadi NumPy array setelah memindahkannya kembali ke CPU.

In [115]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Anda benar, menggunakan `.cpu().numpy()` adalah cara yang tepat untuk mengonversi tensor yang berada di GPU ke NumPy array. Metode `.cpu()` digunakan untuk memindahkan tensor kembali ke CPU, dan kemudian `.numpy()` digunakan untuk mengonversinya menjadi NumPy array. Berikut adalah contohnya:

```python
# Instead, copy the tensor back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
```

Dengan cara ini, Anda berhasil mengonversi tensor yang berada di GPU ke NumPy array setelah memindahkannya kembali ke CPU.

In [116]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Sepertinya Anda ingin menampilkan isi dari tensor yang dipindahkan ke GPU. Untuk menampilkan konten dari `tensor_on_gpu`, Anda dapat mencetaknya. Berikut adalah konten dari `tensor_on_gpu`:

```python
tensor_on_gpu
```

Ini akan mencetak tensor yang dipindahkan ke GPU. Jika Anda memiliki pertanyaan khusus atau jika ada hal lain yang ingin Anda ketahui atau lakukan dengan `tensor_on_gpu`, beri tahu saya!